export const DEFAULT_TRANSFORMATIONS = [
  {
    name: 'Ahmed ElBakry',
    duration: '6 months',
    muscle: ['47.1', '45.5', 'kg'],
    fat: ['22.5', '14.6', '%'],
    type: 'fat-loss',
    story: 'A steady six-month refinement: less body fat, more definition, and a stronger relationship with consistency.',
    images: ['1.jpeg', '2.jpeg', '3.jpeg', '4.jpeg', '5.jpeg', '6.jpeg'],
  },
  {
    name: 'Mahmoud Alaa',
    duration: '3 months',
    muscle: ['38.4', '39.5', 'kg'],
    fat: ['20.8', '11.0', '%'],
    type: 'fat-loss',
    story: 'Three months of work, captured in the details: a leaner frame and a sharper, more athletic silhouette.',
    images: ['1.jpeg', '2.jpeg', '3.jpeg', '4.jpeg', '5.jpeg', '6.jpeg'],
  },
  {
    name: 'Karim Mohamed',
    duration: 'ongoing',
    muscle: ['31.4', '34.2', 'kg'],
    fat: ['17.6', '12.2', '%'],
    type: 'recomposition',
    story: 'A compact, intentional phase of recomposition with muscle moving up as body fat moved down.',
    images: ['1.jpeg', '2.jpeg', '3.jpeg', '4.jpeg', '5.jpeg'],
  },
  {
    name: 'Yossif Ali',
    duration: '1 month',
    muscle: ['43.2', '42.6', 'kg'],
    fat: ['10.2', '8.2', '%'],
    type: 'fat-loss',
    story: 'One focused month, one clear direction: a leaner finish and the early signs of a strong long-term foundation.',
    images: ['1.jpeg', '2.jpeg', '3.jpeg'],
  },
  {
    name: 'Mostafa Ibrahim',
    duration: '6 months',
    muscle: ['33.2', '33.8', 'kg'],
    fat: ['24.9', '16.3', '%'],
    type: 'fat-loss',
    story: 'Six months of patient progress: a meaningful reduction in body fat with muscle mass moving in the right direction.',
    images: ['1.jpeg', '2.jpeg', '3.jpeg', '4.jpeg', '5.jpeg'],
  },
  {
    name: 'Hassan Ramadan',
    duration: 'ongoing',
    muscle: ['33.1', '38.1', 'kg'],
    fat: ['18.9', '14.4', '%'],
    type: 'muscle',
    story: 'Three months of focused training translated into a visible shift in strength, shape, and confidence.',
    images: [
      'WhatsApp Image 2026-08-18 at 8.32.03 PM.jpeg',
      '81f12ee1-93c0-4f62-95b8-1d5284473da7.jpg',
      'WhatsApp Image 2026-08-18 at 8.32.02 PM.jpeg',
    ],
  },
  {
    name: 'Mohamed Amir',
    duration: '2 months',
    muscle: ['42.0', '42.1', 'kg'],
    fat: ['20.5', '14.2', '%'],
    type: 'recomposition',
    story: 'A measurable transformation built from repeatable habits, with body fat trending down while muscle stays protected.',
    images: ['1.jpeg', '2.jpeg', '3.jpeg', '4.jpeg', '5.jpeg'],
  },
];
